
const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS;
const API_URL = process.env.NEXT_PUBLIC_API_URL;
const PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID;

export { CONTRACT_ADDRESS, API_URL, PROJECT_ID };
